### PR TITLE
bgfx examples

### PR DESCRIPTION
**Pull request by code-disaster**
Java ports of bgfx examples to accompany https://github.com/LWJGL/lwjgl3/pull/240.

### CODE REVIEW

**Comment by httpdigest** [comment]
Let's merge this once org.lwjgl:lwjgl-bgfx is in Central.

**Comment by Spasi** [comment]
The latest nightly build includes the bgfx bindings. There have been some breaking changes since this PR, e.g. `bgfx_set_platform_data` is now in the `BGFXPlatform` class.

**Comment by httpdigest** [comment]
Now, the bgfx bindings do some invalid parameter validations. The following usecase is now not possible anymore: https://github.com/bkaradzic/bgfx/blob/master/examples/09-hdr/hdr.cpp#L40-L42
because `bgfx_alloc_transient_vertex_buffer` checks the tvb via `BGFXTransientVertexBuffer.validate(_tvb)` which in turn checks whether DATA has been set, which it has not, because that field will be filled by the bgfx call.

**Comment by code-disaster** [comment]
Yes, this applies to `bgfx_transient_index_buffer_t.data` and `bgfx_transient_vertex_buffer_t.data`.

**Comment by Spasi** [comment]
> because that field will be filled by the bgfx call

Thanks, will be fixed in the next nightly with https://github.com/LWJGL/lwjgl3/commit/78082822105afe30d454f6b7ff1779b1ea2159ad.

**Comment by httpdigest** [comment]
Is there already a consensus as to how LWJGL 3 is going to handle the bgfx shared library? Currently, when you just checkout the lwjgl3-demos repository and download all the maven dependencies, you cannot run bgfx demos without manually building bgfx as a shared library (or downloading it from somewhere else).
I think we should handle the bgfx shared library in the same way that we handle glfw, by building it on a CI server (travis, appveyor) and include it in a natives jar.

**Comment by Spasi** [comment]
I initially thought that bgfx is statically configured for specific backends, but I was wrong. The default build is small enough and supports all backends on a given platform. So yes, I'll setup CI builds.

The builds will be configured with `--with-glfw --with-shared-lib` (and `--with-ovr` on Windows). As always, users will be able to replace the shared library with a custom build (debug, disabled backends for smaller binaries, etc).

**Comment by code-disaster** [comment]
You don't need `--with-glfw`. I didn't manage to compile it when I tried, and I didn't pursue it any further when I found it's not required. The integration with [lwjgl-glfw](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/bgfx/HelloBGFX.java#L40-L76) is simple enough.

`--with-ovr` has the "disadvantage" that, for Oculus owners like me, the damn Oculus Store pops up each time I start a program which links to their SDK, no matter if I want to even use it. I'm not sure if that's a bgfx thing or just the way this works. I could unplug my Rift each time I'm coding, but for now I just opted to leave it be and compile a bgfx.dll without this flag.

In any case, it's nice that LWJGL provides the means to replace the shared lib at any time, if needed.

**Comment by httpdigest** [comment]
I also did not compile with `--with-glfw`, and it seems to work (on Windows).

**Comment by Spasi** [comment]
> You don't need `--with-glfw`.

I'm afraid it's going to break badly under MacOS without `--with-glfw` (which is just an alias for `BGFX_CONFIG_MULTITHREADED=0`). Will try and let you know.

> `--with-ovr` has the "disadvantage" that, for Oculus owners like me, the damn Oculus Store pops up each time I start a program which links to their SDK, no matter if I want to even use it.

OK, will build without it, until that issue is fixed and/or the Oculus user base increases.

**Comment by httpdigest** [comment]
I propose to add this code in Demo.java right below the GLFW window creation to fix window resizing and aspect ratio issues in all demos:
```Java
GLFWFramebufferSizeCallback fbsc;
glfwSetFramebufferSizeCallback(window, fbsc = new GLFWFramebufferSizeCallback() {
	public void invoke(long window, int width, int height) {
		Demo.this.width = width;
		Demo.this.height = height;
		bgfx_reset(width, height, Demo.this.reset);
	}
});
```

**Comment by httpdigest** [comment]
There does not seem to be bgfx natives on Maven/oss.sonatype.org.

**Comment by Spasi** [comment]
Sorry about that, should be OK now.

**Comment by httpdigest** [comment]
Yes, seems to work fine. @code-disaster, could you add the necessary changes to the pom.xml in the profiles section to include the natives, please? Then we can merge the pull request.

**Comment by httpdigest** [comment]
Thanks for your work on porting the bgfx demos!

**Pull request merged**
