### PR TITLE
bugfix for macos

### PR DESCRIPTION
**Pull request by pge76**
corrected macos-classifiers
corrected bgfx noop renderer

### CODE REVIEW

**Comment by pge76** [comment]
did not work for me on macos, had to make these 2 small adjustments

**Comment by httpdigest** [comment]
Thanks!

**Comment by pge76** [comment]
Hi Kai,

ich weiss nicht, wieviel Sinn die Macos Unterstützung in den Demos macht, alle Demos mit OpenGL v3 gehen nicht, da du ein core profile für opengl >2.1 brauchst, und das geht erst ab 3.2, mit dem core profil laufen dann aber wiederum die shader nicht, da dann keine GLSL unter 3.2.0 unterstützt wird, man müsste wohl alle shader umschreiben.

Ich hatte hier Hilfe gesucht, da ein Programm von mir auf meinem Mac nach dem laden der Shader einfach stehen bleibt (keine Fehlermeldung, o.ä.). Auf Windows aber ohne Probleme läuft, aber ich denke da kannst du sicher auch nicht weiterhelfen :)

**Comment by httpdigest** [comment]
Can you name explicitly, which demos do not work on OS X. As far as I see it, the only demos that do not work (because of missing GL 3.2 core profile request) are:
- shader/NoVerticesBSplineDemo
- shader/NoVerticesGridDemo
- shader/NoVerticesPolygonDemo
- shader/NoVerticesProjectedGridDemo
- shadow/ShadowMappingDemo
- textures/Texture2DArrayMipmapping

As far as I see it, all other demos do request a GL >=3.2 core profile, if necessary. Could you test these (and other demos) to verify this? I'd like to fix these to make them also run on OS X.

**Comment by pge76** [comment]
If not mentioned in my list, it works.

FYI, i run a Macbook Pro with OS X El Capitan 10.11.6 with an Intel Iris Pro, if you need that info.
Maximum OpenGL Version for this is 4.1 (https://developer.apple.com/opengl/capabilities/)

I don't have any comparison to a windows pc at the moment, so if anything looks different there, i just cant tell you.

org.lwjgl.demo.game - runs, but shooting is only possible in the top-left quadrant of the screen
org.lwjgl.demo.opengl.SimpleDrawElements runs, but Displays only a red screen, its supposed to display a square afaik 
org.lwjgl.demo.opengl.UniformArrayDemo - does not run, requiring opengl 3.0
org.lwjgl.demo.opengl.fbo.DepthEdgeShaderDemo - runs, but displays the animation only in the lower left quadrant of the window
org.lwjgl.demo.opengl.fbo.EdgeShaderDemo20 - runs, but displays the animation only in the lower left quadrant of the window
org.lwjgl.demo.opengl.fbo.EdgeShaderMultisampleDemo20 - runs, but same as last one, plus here the rest of the screen flickers black/white
org.lwjgl.demo.opengl.fbo.MultisampledFbo2Demo - runs, but just displays a slowly rotating black square
org.lwjgl.demo.opengl.fbo.MultisampledFboDemo - runs, but with same problem as the last one.
org.lwjgl.demo.opengl.geometry.* - runs, but displays only in the lower left quadrant of the screen
org.lwgl.demo.opengl.raytracing.AtomicDemo - does not run, OpenGL requested version too high
org.lwgl.demo.opengl.raytracing.Demo - does not run, OpenGL requested version too high
org.lwgl.demo.opengl.raytracing.DemoSsbO - does not run, OpenGL requested version too high
org.lwgl.demo.opengl.raytracing.DemoSsboTrianglesStacklessKdTree - does not run, OpenGL requested version too high
org.lwgl.demo.opengl.raytracing.HybridDemo* - does not run, OpenGL requested version too high
org.lwgl.demo.opengl.shader - you mentioned already
org.lwgl.demo.opengl.shadow - you mentioned already
org.lwgl.demo.opengl.texture.Texture2DArrayMipmapping - you mentioned already
org.lwgl.demo.textures.SimpleProceduralTextureDemo - runs, but displays only a half black  & white screen
org.lwjgl.demo.vulkan - obviously do not work, i do not have any vulkan implementation installed

Just now i figured, that the bug with rendering happening only in a quarter of the screen, can be fixed via resizing the screen once, after that it works just fine.

**Comment by httpdigest** [comment]
Thanks a lot for the very detailed list. All demos with `does not run, OpenGL requested version too high` are known to not work on OS X, because Apple never bothered to implement OpenGL 4.3.
I will take care of the rest.

**Pull request merged**
